# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RightElement(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, since: int=None, until: date=None, duration: int=None, source: str=None):  # noqa: E501
        """RightElement - a model defined in Swagger

        :param since: The since of this RightElement.  # noqa: E501
        :type since: int
        :param until: The until of this RightElement.  # noqa: E501
        :type until: date
        :param duration: The duration of this RightElement.  # noqa: E501
        :type duration: int
        :param source: The source of this RightElement.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            'since': int,
            'until': date,
            'duration': int,
            'source': str
        }

        self.attribute_map = {
            'since': 'since',
            'until': 'until',
            'duration': 'duration',
            'source': 'source'
        }

        self._since = since
        self._until = until
        self._duration = duration
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'RightElement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RightElement of this RightElement.  # noqa: E501
        :rtype: RightElement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def since(self) -> int:
        """Gets the since of this RightElement.


        :return: The since of this RightElement.
        :rtype: int
        """
        return self._since

    @since.setter
    def since(self, since: int):
        """Sets the since of this RightElement.


        :param since: The since of this RightElement.
        :type since: int
        """

        self._since = since

    @property
    def until(self) -> date:
        """Gets the until of this RightElement.


        :return: The until of this RightElement.
        :rtype: date
        """
        return self._until

    @until.setter
    def until(self, until: date):
        """Sets the until of this RightElement.


        :param until: The until of this RightElement.
        :type until: date
        """

        self._until = until

    @property
    def duration(self) -> int:
        """Gets the duration of this RightElement.


        :return: The duration of this RightElement.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this RightElement.


        :param duration: The duration of this RightElement.
        :type duration: int
        """

        self._duration = duration

    @property
    def source(self) -> str:
        """Gets the source of this RightElement.


        :return: The source of this RightElement.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this RightElement.


        :param source: The source of this RightElement.
        :type source: str
        """

        self._source = source
