---
swagger: "2.0"
info:
  description: "More on: https://github.com/MateuszGrabuszynski/ict-infostradka"
  version: "0.0.1"
  title: "Infostradka"
  termsOfService: ""
  contact:
    email: "mateusz.grabuszynski@student.put.poznan.pl"
  license:
    name: "MIT"
    url: "https://github.com/MateuszGrabuszynski/ict-infostradka/blob/master/LICENSE"
host: "0.0.0.0"
basePath: "/"
schemes:
- "http"
paths:
  /api:
    get:
      tags:
      - "api"
      summary: "Returns json with all rotator elements"
      description: ""
      operationId: "get_elements"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Getting rotator elements finished successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Rotator"
        400:
          description: "Pulling rotator elements caused error"
      x-swagger-router-controller: "swagger_server.controllers.api_controller"
definitions:
  LeftContent:
    type: "object"
    properties:
      source:
        type: "string"
      subtitles:
        type: "string"
    example:
      subtitles: "subtitles"
      source: "source"
  LeftElement:
    type: "object"
    properties:
      since:
        type: "integer"
        format: "date"
      until:
        type: "string"
        format: "date"
      duration:
        type: "integer"
      type:
        type: "string"
        default: "www"
        enum:
        - "image"
        - "html"
        - "www"
        - "video"
        - "stream"
      content:
        type: "array"
        items:
          $ref: "#/definitions/LeftContent"
    example:
      duration: 6
      until: "2000-01-23"
      type: "www"
      content:
      - subtitles: "subtitles"
        source: "source"
      - subtitles: "subtitles"
        source: "source"
      since: 0
  RightElement:
    type: "object"
    properties:
      since:
        type: "integer"
        format: "date"
      until:
        type: "string"
        format: "date"
      duration:
        type: "integer"
      source:
        type: "string"
    example:
      duration: 5
      until: "2000-01-23"
      source: "source"
      since: 1
  NewsElement:
    type: "object"
    properties:
      since:
        type: "integer"
        format: "date"
      until:
        type: "string"
        format: "date"
      duration:
        type: "integer"
      title:
        type: "string"
      content:
        type: "string"
    example:
      duration: 2
      until: "2000-01-23"
      title: "title"
      content: "content"
      since: 5
  Rotator:
    type: "object"
    properties:
      left:
        type: "array"
        items:
          $ref: "#/definitions/LeftElement"
      right:
        type: "array"
        items:
          $ref: "#/definitions/RightElement"
      news:
        type: "array"
        items:
          $ref: "#/definitions/NewsElement"
    example:
      news:
      - duration: 2
        until: "2000-01-23"
        title: "title"
        content: "content"
        since: 5
      - duration: 2
        until: "2000-01-23"
        title: "title"
        content: "content"
        since: 5
      left:
      - duration: 6
        until: "2000-01-23"
        type: "www"
        content:
        - subtitles: "subtitles"
          source: "source"
        - subtitles: "subtitles"
          source: "source"
        since: 0
      - duration: 6
        until: "2000-01-23"
        type: "www"
        content:
        - subtitles: "subtitles"
          source: "source"
        - subtitles: "subtitles"
          source: "source"
        since: 0
      right:
      - duration: 5
        until: "2000-01-23"
        source: "source"
        since: 1
      - duration: 5
        until: "2000-01-23"
        source: "source"
        since: 1
